name: Gem Test

on:
  push:
    branches:
    - master
    - tmp/*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.x', '3.x' ]
    name: Test on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@master
      - name: Setup ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Build and test
        run: |
          bundle install
          ruby -Ilib:test tests/test_simple.rb
