name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6.3
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.3
    - name: Build and test with Rake
      run: |
        gem build erb2slim.gemspec
        ruby -Ilib:test tests/test_simple.rb
